### ISSUE TITLE
import protocol in unittests

### ISSUE THREAD

**Issue by lambe** [PythonOptimizers/NLP.py#66]
Which of the following is preferable in the unit tests using pysparse / cysparse and why?
```
        pytest.importorskip("nlp.model.amplmodel")
        pytest.importorskip("cysparse")
```
vs.
```
        pytest.importorskip("nlp.model.cysparsemodel")
```
As a related question, why does the first one even work, given that the pysparsemodel and cysparsemodel classes are in separate files?

**Comment by dpo** [comment]
Note that PySparseModel and CySparseModel are two unrelated classes, except for the fact that they both inherit from NLPModel.

It's not clear to me that either way is "better" and it's a point we've discussed before. Currently, the model classes aren't really organized according to anything in particular. They should at least be ordered in some way, either by derivative provider (NLPModel, AmplModel, AdolcModel, ...) or by matrix storage format (SciPyModel, PySparseModle, CySparseModel, ...).

**Comment by lambe** [comment]
Ok, just curious. Closing the issue since it's just a style question and both work in unit testing.
