### ISSUE TITLE
Negative curvature in TRON

### ISSUE THREAD

**Issue by lambe** [PythonOptimizers/NLP.py#73]
When we solve HS060 with Auglag and N-Y backtracking turned on in TRON, the program returns an error that the search direction used in the backtracking is not a descent direction. I traced this problem through the code and found that CG discovers a direction of negative curvature in the Hessian. However, this direction is not returned as the search direction for the next projected line search. The following snippet from pcg.py (lines 167-185) explains why:

``` python
            if pHp <= 0 and radius is None:
                # p is direction of singularity or negative curvature.
                self.status = 'infinite descent'
                snorm2 = 0
                self.dir = p
                self.pHp = pHp
                infDescent = True
                continue

            # Compute CG steplength.
            alpha = ry / pHp if pHp != 0 else np.inf

            if radius is not None and (pHp <= 0 or alpha > sigma):
                # p leads past the trust-region boundary. Move to the boundary.
                s += sigma * p
                snorm2 = radius * radius
                self.status = 'trust-region boundary active'
                onBoundary = True
                continue
```

Since we do have a trust region radius, only the second `if` block is considered. It seems that the resulting direction `s` is not a descent direction with respect to the gradient `self.g`, but the infinite descent direction `p` is. What should be the correct behaviour in this case?

**Comment by dpo** [comment]
In CG, each step is a descent direction as long as you don't hit negative curvature. So up until just before the line `s += sigma * p`, the step `s` must be a descent direction. If `p` is also a descent direction (in addition to being a direction of negative curvature), the only way that the resulting `s` could not be a descent direction is if `sigma` were negative. That would be a bug. Could I ask you to go in there with the debugger and check that indeed:
* `dot(g,s) < 0`
* `dot(g,p) < 0`
* `sigma > 0`

**Comment by dpo** [comment]
ps: we're following Algorithm 7.5.1 (p. 205) of the trust-region book (available on the 4th floor).

**Comment by lambe** [comment]
Those tests all pass. I suspect it's what we pass to the CG algorithm, not the CG algorithm itself.

**Comment by dpo** [comment]
Can you point to the line where the problem occurs in TRON?

**Comment by lambe** [comment]
The exception is thrown on line 493, when the ArmijoLineSearch checks the slope for the direction s.

**Comment by lambe** [comment]
I looked at the search directions more carefully and it looks like the sum of the CG output and the Cauchy point step is a descent direction. Therefore, I think the bug is in the projected line search. 

I think it is related to the fact that we have a negative curvature direction in the step, so if we take a large enough step, we can overcome `np.dot(g, s) > 0`

**Comment by dpo** [comment]
If dot(g,s) < 0, then dot(g, ts) <0 for any t > 0.

**Comment by lambe** [comment]
I think I know what is going on: the bound projection is causing the projected step to be a direction of increase. In other words, `dot(g,s) < 0` but `dot(g,P[x + ts] - x) > 0` for some value of `t > 0`. This isn't picked up in the current code.

**Comment by dpo** [comment]
Yes, that is indeed possible. If CG reported negative curvature and there are bound constraints, we should probably skip over the linesearch and update the trust-region radius.

**Comment by lambe** [comment]
What about adding an extra stopping condition on the linesearch to enforce `dot(g,P[x + ts] - x) < 0` explicitly? The worst case is that if `t` is very small, we're close to the Cauchy point, so convergence won't be affected.

**Comment by dpo** [comment]
The problem is that there may not exist such a t if `x` is on the boundary. See, e.g., Fig. 1 of http://www.mit.edu/~dimitrib/ProjectedNewton.pdf.

**Comment by lambe** [comment]
In our code, this can't happen because if x is on the boundary, that component is fixed in the CG solve. Also note that the example in Fig. 1 of the paper is a convex QP, so this is not just a negative curvature problem. 

I think what we can do instead is backtrack to the first breakpoint: `brptmin` in the code. If we cannot accept any t larger than `brptmin`, then we accept `t = brptmin` which will succeed by definition since the search direction is always a descent direction if you remove the projection part.

**Comment by dpo** [comment]
Yes unless `brptmin` is zero in which case we should fall back on the trust-region update and reject the step. In the figure in the paper above, `brptmin` is zero. If it can happen with convex models, it can also happen when there's negative curvature.

**Comment by lambe** [comment]
Closing the issue since the fix was introduced in a pull request and merged.
